"""
Graph visualizer for module and lineage graphs.
Produces both static Graphviz SVG/PNG and interactive PyVis HTML outputs.

Lineage graph: transformation nodes are collapsed into direct dataset→dataset
edges labelled with the transformation name, giving a clean data-flow view.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import networkx as nx


# ── colour palette ────────────────────────────────────────────────────────────
_COLORS = {
    "source":      "#4CAF50",   # green  – raw source (ecom.raw_*)
    "staging":     "#2196F3",   # blue   – staging model (stg_*)
    "mart":        "#F44336",   # red    – mart / sink
    "mid":         "#90CAF9",   # light blue – other intermediate
    "transform":   "#FF9800",   # orange – transformation node (when shown)
    "module_py":   "#9C27B0",
    "module_sq":   "#2196F3",
    "module_ya":   "#607D8B",
    "module_def":  "#78909C",
    "edge_data":   "#4CAF50",
    "edge_import": "#9C27B0",
    "edge_def":    "#90A4AE",
}

_TRUST_BORDER = {
    "sqlglot":     "#1565C0",
    "tree_sitter": "#1565C0",
    "yaml_parse":  "#1565C0",
    "llm":         "#E65100",
    "heuristic":   "#757575",
}


def _short(path: str) -> str:
    parts = Path(path).parts
    return "/".join(parts[-2:]) if len(parts) >= 2 else path


def _dataset_tier(node_id: str) -> str:
    """Classify a dataset node into source / staging / mart."""
    n = node_id.lower()
    if n.startswith("ecom.") or n.startswith("raw_"):
        return "source"
    if n.startswith("stg_"):
        return "staging"
    return "mart"


def _border_color(node_data: dict) -> str:
    prov = node_data.get("provenance", {})
    ev = prov.get("evidence_type", "") if isinstance(prov, dict) else ""
    return _TRUST_BORDER.get(ev, "#455A64")


def _tooltip(node_id: str, node_data: dict) -> str:
    """Build a plain-text tooltip (PyVis escapes HTML, so we use plain text)."""
    node_type = node_data.get("node_type", "unknown")
    prov = node_data.get("provenance", {}) or {}
    ev   = prov.get("evidence_type", "?")
    conf = prov.get("confidence", 0.0)
    lr   = prov.get("line_range")
    src  = prov.get("source_file", "")
    line_part = f":{lr[0]}-{lr[1]}" if lr else ""
    purpose = node_data.get("purpose_statement", "")

    if node_type == "dataset":
        tier = _dataset_tier(node_id)
        type_label = {"source": "Raw source table", "staging": "Staging dataset", "mart": "Mart / output table"}.get(tier, "Dataset")
    elif node_type == "transformation":
        type_label = "dbt transformation model"
    else:
        lang = node_data.get("language", "")
        type_label = f"{lang} module" if lang else "Module"

    lines = [
        f"◆ {_short(node_id)}",
        f"Type : {type_label}",
        f"Kind : {node_type}",
    ]
    if node_data.get("generated"):
        lines.append(f"Note : Generated by dbt model '{node_data.get('generator', '?')}' — no source inputs")
    if purpose:
        lines.append("")
        lines.append(purpose[:220])
    lines += [
        "",
        f"Evidence   : {ev}",
        f"Confidence : {conf:.2f}",
    ]
    if src:
        lines.append(f"File       : {src}{line_part}")
    return "\n".join(lines)


def _build_collapsed_lineage(graph: nx.DiGraph) -> nx.DiGraph:
    """
    Collapse transformation nodes into direct dataset→dataset edges.

    dbt_model:X nodes are removed; their CONSUMES/PRODUCES edges become
    a single direct edge from each source dataset to each target dataset,
    labelled with the transformation name.

    Transformations with no source datasets (e.g. metricflow_time_spine)
    are kept as isolated output nodes so they remain visible.
    """
    collapsed = nx.DiGraph()

    for node_id, data in graph.nodes(data=True):
        if data.get("node_type") == "dataset":
            collapsed.add_node(node_id, **data)

    for node_id, data in graph.nodes(data=True):
        if data.get("node_type") != "transformation":
            continue
        transform_label = node_id.replace("dbt_model:", "")

        sources = [u for u, v in graph.in_edges(node_id)
                   if graph.nodes[u].get("node_type") == "dataset"]
        targets = [v for u, v in graph.out_edges(node_id)
                   if graph.nodes[v].get("node_type") == "dataset"]

        if not sources:
            # No inputs — mark target datasets as "generated" so the UI can flag them
            for tgt in targets:
                if tgt in collapsed:
                    collapsed.nodes[tgt]["generated"] = True
                    collapsed.nodes[tgt]["generator"] = transform_label
            continue

        for src in sources:
            for tgt in targets:
                if src != tgt:
                    prov = data.get("provenance", {})
                    collapsed.add_edge(
                        src, tgt,
                        label=transform_label,
                        edge_type="data_flow",
                        source_file=data.get("source_file", ""),
                        line_range=data.get("line_range"),
                        provenance=prov,
                        confidence=prov.get("confidence", 1.0) if isinstance(prov, dict) else 1.0,
                    )

    return collapsed


# ─────────────────────────────────────────────────────────────────────────────
# Graphviz (static SVG / PNG)
# ─────────────────────────────────────────────────────────────────────────────

def _gv_id(node_id: str) -> str:
    """Sanitize a node ID for Graphviz (colons are port separators)."""
    return node_id.replace(":", "__").replace("/", "_").replace(".", "_")


def render_graphviz(
    graph: nx.DiGraph,
    graph_type: str,
    output_path: str,
    fmt: str = "svg",
    collapse_transforms: bool = True,
) -> str:
    try:
        import graphviz as gv
    except ImportError:
        raise ImportError("graphviz Python package not installed. Run: uv add graphviz")

    if graph_type == "lineage" and collapse_transforms:
        g = _build_collapsed_lineage(graph)
    else:
        g = graph

    dot = gv.Digraph(
        name=graph_type,
        graph_attr={
            "rankdir": "LR",
            "bgcolor": "#1E1E2E",
            "fontname": "Helvetica",
            "fontcolor": "#CDD6F4",
            "pad": "0.6",
            "splines": "ortho",
            "nodesep": "0.5",
            "ranksep": "1.2",
        },
        node_attr={
            "style": "filled,rounded",
            "fontname": "Helvetica",
            "fontsize": "11",
            "fontcolor": "#FFFFFF",
            "penwidth": "2",
            "width": "1.6",
            "height": "0.5",
        },
        edge_attr={
            "fontname": "Helvetica",
            "fontsize": "9",
            "fontcolor": "#B0BEC5",
            "arrowsize": "0.7",
            "color": _COLORS["edge_data"],
        },
    )

    def add_rank(nodes, rank):
        with dot.subgraph() as s:
            s.attr(rank=rank)
            for n in nodes:
                s.node(_gv_id(n))

    sources, staging, marts = [], [], []
    for node_id in g.nodes():
        tier = _dataset_tier(node_id)
        if tier == "source":
            sources.append(node_id)
        elif tier == "staging":
            staging.append(node_id)
        else:
            marts.append(node_id)

    for node_id, data in g.nodes(data=True):
        if graph_type == "lineage":
            tier = _dataset_tier(node_id)
            fill = _COLORS.get(tier, _COLORS["mid"])
        else:
            lang = data.get("language", "")
            fill = _COLORS.get(f"module_{lang[:2]}", _COLORS["module_def"])
        border = _border_color(data)
        shape = "box" if data.get("node_type") == "transformation" else "ellipse"
        dot.node(
            _gv_id(node_id),
            label=_short(node_id),
            fillcolor=fill,
            color=border,
            shape=shape,
            tooltip=_tooltip(node_id, data),
        )

    add_rank(sources, "source")
    add_rank(staging, "same")
    add_rank(marts, "sink")

    for src, tgt, edata in g.edges(data=True):
        label = edata.get("label", edata.get("edge_type", ""))
        conf  = edata.get("confidence", 1.0)
        style = "dashed" if conf < 0.7 else "solid"
        src_file = edata.get("source_file", "")
        lr = edata.get("line_range")
        edge_tip = f"{label}\nfile={src_file}"
        if lr:
            edge_tip += f":{lr[0]}-{lr[1]}"
        dot.edge(
            _gv_id(src), _gv_id(tgt),
            label=label,
            style=style,
            tooltip=edge_tip,
            color=_COLORS["edge_data"],
        )

    out = dot.render(output_path, format=fmt, cleanup=True)
    return out


# ─────────────────────────────────────────────────────────────────────────────
# PyVis (interactive HTML)
# ─────────────────────────────────────────────────────────────────────────────

def render_pyvis(
    graph: nx.DiGraph,
    graph_type: str,
    output_path: str,
    height: str = "860px",
    collapse_transforms: bool = True,
) -> str:
    try:
        from pyvis.network import Network
    except ImportError:
        raise ImportError("pyvis not installed. Run: uv add pyvis")

    if graph_type == "lineage" and collapse_transforms:
        g = _build_collapsed_lineage(graph)
    else:
        g = graph

    net = Network(
        height=height,
        width="100%",
        directed=True,
        bgcolor="#1E1E2E",
        font_color="#CDD6F4",
        notebook=False,
    )

    net.set_options(json.dumps({
        "physics": {
            "enabled": True,
            "solver": "forceAtlas2Based",
            "forceAtlas2Based": {
                "gravitationalConstant": -120,
                "springLength": 160,
                "springConstant": 0.05,
                "damping": 0.9,
            },
            "stabilization": {"iterations": 200},
        },
        "edges": {
            "arrows": {"to": {"enabled": True, "scaleFactor": 0.7}},
            "smooth": {"type": "cubicBezier", "forceDirection": "horizontal", "roundness": 0.4},
            "font": {"size": 10, "color": "#B0BEC5", "strokeWidth": 0},
            "color": {"inherit": False},
            "width": 1.5,
        },
        "nodes": {
            "font": {"size": 13, "bold": True},
            "borderWidth": 2,
            "borderWidthSelected": 4,
        },
        "interaction": {
            "hover": True,
            "tooltipDelay": 80,
            "selectConnectedEdges": True,
            "navigationButtons": True,
            "keyboard": True,
        },
        "layout": {"improvedLayout": True},
    }))

    tier_size = {"source": 18, "staging": 22, "mart": 28, "mid": 20}

    for node_id, data in g.nodes(data=True):
        if graph_type == "lineage":
            tier = _dataset_tier(node_id)
            color = _COLORS.get(tier, _COLORS["mid"])
            size  = tier_size.get(tier, 20)
            shape = "ellipse"
            # Generated nodes (no inputs, e.g. metricflow_time_spine) get a distinct style
            if data.get("generated"):
                color = "#FF9800"   # orange — generated/computed, no source
                size  = 20
        else:
            lang  = data.get("language", "")
            color = _COLORS.get(f"module_{lang[:2]}", _COLORS["module_def"])
            size  = 20
            shape = "dot"

        border = _border_color(data)
        title  = _tooltip(node_id, data)
        label  = _short(node_id)

        net.add_node(
            node_id,
            label=label,
            title=title,
            color={"background": color, "border": border,
                   "highlight": {"background": "#FFEB3B", "border": "#F57F17"},
                   "hover":     {"background": "#FFF9C4", "border": "#F57F17"}},
            shape=shape,
            size=size,
            font={"color": "#FFFFFF", "size": 13},
        )

    for src, tgt, edata in g.edges(data=True):
        label    = edata.get("label", edata.get("edge_type", ""))
        conf     = edata.get("confidence", 1.0)
        dashes   = conf < 0.7
        src_file = edata.get("source_file", "")
        lr       = edata.get("line_range")

        # Human-readable edge description
        edge_type = edata.get("edge_type", "")
        if edge_type == "consumes":
            edge_desc = f"'{_short(src)}' is read as input by transformation '{label}'"
        elif edge_type == "produces":
            edge_desc = f"transformation '{label}' writes out '{_short(tgt)}'"
        elif label:
            edge_desc = f"'{_short(src)}' flows into '{_short(tgt)}' via dbt model '{label}'"
        else:
            edge_desc = f"'{_short(src)}' → '{_short(tgt)}'"

        tip  = f"◆ {_short(src)} → {_short(tgt)}\n"
        tip += f"Edge type     : data flow\n"
        tip += f"Via dbt model : {label}\n" if label else ""
        tip += f"Meaning       : {edge_desc}\n"
        tip += f"\nConfidence : {conf:.2f}"
        if src_file:
            tip += f"\nFile       : {src_file}"
            if lr:
                tip += f":{lr[0]}-{lr[1]}"

        net.add_edge(
            src, tgt,
            label=label,
            title=tip,
            color=_COLORS["edge_data"],
            dashes=dashes,
            width=2 if conf >= 0.8 else 1,
        )

    _inject_highlight_js(net, output_path, graph_type, collapsed=collapse_transforms)
    return output_path


def _legend_html(graph_type: str, collapsed: bool = True) -> str:
    if graph_type == "lineage":
        items = [
            ("●", _COLORS["source"],  "Raw source dataset (ecom.raw_*)"),
            ("●", _COLORS["staging"], "Staging dataset (stg_*)"),
            ("●", _COLORS["mart"],    "Mart / output dataset"),
            ("●", "#FF9800",          "Generated dataset (no source inputs)"),
        ]
        if collapsed:
            items.append(("─", _COLORS["edge_data"], "Edge label = dbt model that transforms the data"))
        else:
            items += [
                ("■", _COLORS["transform"], "dbt transformation model (SQL file)"),
                ("─", _COLORS["edge_data"],  "consumes — dataset feeds into transformation"),
                ("─", "#4CAF50",             "produces — transformation writes out dataset"),
            ]
        items.append(("- -", "#90A4AE", "Dashed edge = low-confidence (< 0.7)"))
    else:
        items = [
            ("●", _COLORS["module_py"],  "Python module"),
            ("●", _COLORS["module_sq"],  "SQL module"),
            ("●", _COLORS["module_ya"],  "YAML config"),
            ("●", _COLORS["module_def"], "Other module"),
            ("─", _COLORS["edge_import"], "imports relationship"),
        ]

    rows = "".join(
        f'<div style="display:flex;align-items:center;gap:8px;margin:4px 0">'
        f'<span style="color:{color};font-size:18px;line-height:1">{sym}</span>'
        f'<span>{desc}</span></div>'
        for sym, color, desc in items
    )
    return f"""
<div id="legend" style="
    position:fixed; bottom:16px; left:16px; z-index:999;
    background:#2A2A3E; border:1px solid #444; border-radius:8px;
    padding:12px 16px; font-family:Helvetica,sans-serif;
    font-size:12px; color:#CDD6F4; min-width:280px;
    box-shadow:0 2px 8px rgba(0,0,0,0.5);">
  <div style="font-weight:bold;margin-bottom:8px;font-size:13px">Legend</div>
  {rows}
  <div style="margin-top:8px;border-top:1px solid #444;padding-top:8px;font-size:11px;color:#888">
    Click a node to highlight its neighbours · Click background to reset
  </div>
</div>
"""


def _inject_highlight_js(net, output_path: str, graph_type: str = "lineage", collapsed: bool = True) -> None:
    """Save the PyVis graph and inject neighbour-highlight JavaScript and legend."""
    net.save_graph(output_path)

    highlight_js = """
<script type="text/javascript">
network.on("click", function(params) {
    if (params.nodes.length > 0) {
        var selectedNode = params.nodes[0];
        var connectedNodes = network.getConnectedNodes(selectedNode);
        var connectedEdges = network.getConnectedEdges(selectedNode);
        var allNodes = network.body.data.nodes.get();
        var allEdges = network.body.data.edges.get();
        var updateNodes = [];
        var updateEdges = [];
        allNodes.forEach(function(node) {
            if (node.id === selectedNode) {
                updateNodes.push({id: node.id, opacity: 1.0, borderWidth: 4});
            } else if (connectedNodes.includes(node.id)) {
                updateNodes.push({id: node.id, opacity: 0.9, borderWidth: 3});
            } else {
                updateNodes.push({id: node.id, opacity: 0.15});
            }
        });
        allEdges.forEach(function(edge) {
            if (connectedEdges.includes(edge.id)) {
                updateEdges.push({id: edge.id, width: 3, color: {opacity: 1.0}});
            } else {
                updateEdges.push({id: edge.id, width: 1, color: {opacity: 0.1}});
            }
        });
        network.body.data.nodes.update(updateNodes);
        network.body.data.edges.update(updateEdges);
    } else {
        var allNodes = network.body.data.nodes.get();
        var allEdges = network.body.data.edges.get();
        network.body.data.nodes.update(allNodes.map(function(n) {
            return {id: n.id, opacity: 1.0, borderWidth: 2};
        }));
        network.body.data.edges.update(allEdges.map(function(e) {
            return {id: e.id, width: 2, color: {opacity: 1.0}};
        }));
    }
});
</script>
"""
    with open(output_path, "r") as f:
        html = f.read()
    html = html.replace("</body>", _legend_html(graph_type, collapsed) + highlight_js + "\n</body>")
    with open(output_path, "w") as f:
        f.write(html)


# ─────────────────────────────────────────────────────────────────────────────
# CLI entry point
# ─────────────────────────────────────────────────────────────────────────────

def visualize(
    graph_path: str,
    graph_type: str,
    output_dir: str,
    formats: list[str] | None = None,
    collapse_transforms: bool = True,
) -> list[str]:
    import sys
    sys.path.insert(0, str(Path(__file__).parent.parent))
    from analyzers.graph_serializer import GraphSerializer

    if formats is None:
        formats = ["svg", "html"]

    graph = GraphSerializer.deserialize_graph(graph_path)
    os.makedirs(output_dir, exist_ok=True)
    stem = f"{graph_type}_graph"
    outputs = []

    for fmt in formats:
        out_base = os.path.join(output_dir, stem)
        if fmt == "html":
            path = render_pyvis(graph, graph_type, out_base + ".html", collapse_transforms=collapse_transforms)
        else:
            path = render_graphviz(graph, graph_type, out_base, fmt=fmt, collapse_transforms=collapse_transforms)
        outputs.append(path)
        print(f"  ✓ {fmt.upper():4s}  →  {path}")

    return outputs


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Visualize Cartographer graphs")
    parser.add_argument("graph_path", help="Path to *_graph.json")
    parser.add_argument("--type", choices=["lineage", "module"], default="lineage", dest="graph_type")
    parser.add_argument("--output-dir", default=".")
    parser.add_argument("--formats", nargs="+", default=["svg", "html"], choices=["svg", "png", "html"])
    args = parser.parse_args()

    print(f"\nVisualizing {args.graph_type} graph: {args.graph_path}")
    visualize(args.graph_path, args.graph_type, args.output_dir, args.formats)
