"""Unit tests for OnboardingBriefGenerator."""

import pytest
from datetime import datetime

from agents.onboarding_brief_generator import OnboardingBriefGenerator
from models import ProvenanceMetadata


@pytest.fixture
def sample_provenance():
    """Create sample provenance metadata."""
    return ProvenanceMetadata(
        evidence_type="heuristic",
        source_file="lineage_graph",
        confidence=0.85,
        resolution_status="resolved"
    )


@pytest.fixture
def sample_day_one_answers(sample_provenance):
    """Create sample Day-One answers."""
    return {
        'ingestion_path': {
            'answer': 'Data enters the system through three primary sources: users_table (PostgreSQL), '
                     'events.csv (file), and api_data (REST API). The main ingestion point is in '
                     '`src/ingestion/loader.py:45-67`.',
            'evidence': [
                {
                    'type': 'data_source',
                    'name': 'users_table',
                    'storage_type': 'table',
                    'file': 'src/ingestion/loader.py',
                    'line_range': (45, 50),
                    'confidence': 1.0,
                    'evidence_type': 'tree_sitter'
                },
                {
                    'type': 'ingestion_transformation',
                    'transformation_id': 'load_users',
                    'transformation_type': 'pandas',
                    'file': 'src/ingestion/loader.py',
                    'line_range': (45, 67),
                    'sources': ['users_table'],
                    'confidence': 0.95,
                    'evidence_type': 'tree_sitter'
                }
            ],
            'provenance': sample_provenance
        },
        'critical_outputs': {
            'answer': 'The system produces two critical outputs: analytics_report (BigQuery table) '
                     'and dashboard_data.json (file). These are generated by `src/output/exporter.py:120-145`.',
            'evidence': [
                {
                    'type': 'critical_output_dataset',
                    'name': 'analytics_report',
                    'storage_type': 'table',
                    'file': 'src/output/exporter.py',
                    'line_range': (120, 130),
                    'confidence': 0.9,
                    'evidence_type': 'sqlglot'
                }
            ],
            'provenance': sample_provenance
        },
        'blast_radius': {
            'answer': 'If users_table breaks, it would affect 15 downstream components including '
                     'all analytics pipelines and reporting dashboards.',
            'evidence': [
                {
                    'type': 'lineage_blast_radius',
                    'node': 'users_table',
                    'affected_count': 15,
                    'affected_list': ['transform_1', 'transform_2', 'analytics_report'],
                    'file': 'users_table',
                    'confidence': 0.95,
                    'evidence_type': 'heuristic'
                }
            ],
            'provenance': sample_provenance
        },
        'logic_distribution': {
            'answer': 'Business logic is distributed across 3 domains: Data Processing (8 modules), '
                     'Analytics (5 modules), and Reporting (3 modules).',
            'evidence': [
                {
                    'type': 'domain_cluster',
                    'domain': 'Data Processing',
                    'module_count': 8,
                    'representative_modules': [
                        {'path': 'src/processing/transform.py', 'purpose': 'Data transformation', 'complexity': 50}
                    ],
                    'confidence': 0.75,
                    'evidence_type': 'heuristic'
                }
            ],
            'provenance': sample_provenance
        },
        'change_velocity': {
            'answer': 'The most frequently changed files are src/config.py (45 commits), '
                     'src/processing/transform.py (32 commits), and src/api/routes.py (28 commits).',
            'evidence': [
                {
                    'type': 'high_velocity_module',
                    'path': 'src/config.py',
                    'change_velocity': 45,
                    'purpose': 'Configuration settings',
                    'domain_cluster': 'Core',
                    'file': 'src/config.py',
                    'line_range': (1, 30),
                    'confidence': 1.0,
                    'evidence_type': 'heuristic'
                }
            ],
            'provenance': sample_provenance
        }
    }


@pytest.fixture
def sample_analysis_metadata():
    """Create sample analysis metadata."""
    return {
        'timestamp': datetime(2024, 3, 15, 10, 30, 0),
        'repository_path': '/path/to/repo',
        'total_modules': 25,
        'total_datasets': 10,
        'total_transformations': 15,
        'analysis_duration': '5m 23s'
    }


def test_onboarding_brief_generator_initialization():
    """Test OnboardingBriefGenerator can be initialized."""
    generator = OnboardingBriefGenerator()
    assert generator is not None


def test_generate_complete_brief(sample_day_one_answers, sample_analysis_metadata):
    """Test generating complete onboarding_brief.md."""
    generator = OnboardingBriefGenerator()
    
    result = generator.generate(
        day_one_answers=sample_day_one_answers,
        analysis_metadata=sample_analysis_metadata
    )
    
    # Verify result is a string
    assert isinstance(result, str)
    assert len(result) > 0
    
    # Verify header
    assert "# Onboarding Brief - Day-One Questions" in result
    
    # Verify all five questions are present
    assert "## Question 1: Where does data come from?" in result
    assert "## Question 2: What are the critical outputs?" in result
    assert "## Question 3: What happens if critical components break?" in result
    assert "## Question 4: Where does business logic live?" in result
    assert "## Question 5: What changes most often?" in result
    
    # Verify metadata section
    assert "## Analysis Metadata" in result
    assert "2024-03-15 10:30:00" in result
    assert "/path/to/repo" in result
    assert "25" in result  # total_modules
    
    # Verify coverage summary
    assert "## Coverage Summary" in result


def test_write_metadata(sample_analysis_metadata):
    """Test writing metadata section."""
    generator = OnboardingBriefGenerator()
    
    result = generator._write_metadata(sample_analysis_metadata)
    
    assert "## Analysis Metadata" in result
    assert "2024-03-15 10:30:00" in result
    assert "/path/to/repo" in result
    assert "Modules Analyzed:** 25" in result
    assert "Datasets Identified:** 10" in result
    assert "Transformations Tracked:** 15" in result
    assert "Analysis Duration:** 5m 23s" in result


def test_write_question_section(sample_day_one_answers):
    """Test writing a single question section."""
    generator = OnboardingBriefGenerator()
    
    result = generator._write_question_section(
        question_number=1,
        question_title="Where does data come from?",
        answer_data=sample_day_one_answers['ingestion_path']
    )
    
    assert "## Question 1: Where does data come from?" in result
    assert "### Answer" in result
    assert "Data enters the system" in result
    assert "### Evidence" in result
    assert "### Confidence" in result
    assert "Evidence Type:** heuristic" in result
    assert "Confidence Score:** 0.85" in result


def test_format_evidence_citations_data_source():
    """Test formatting data source evidence citations."""
    generator = OnboardingBriefGenerator()
    
    evidence = [
        {
            'type': 'data_source',
            'name': 'users_table',
            'storage_type': 'table',
            'file': 'src/loader.py',
            'line_range': (10, 20),
            'confidence': 1.0
        }
    ]
    
    result = generator.format_evidence_citations(evidence)
    
    assert "**Data Source:** `users_table`" in result
    assert "`src/loader.py`:10-20" in result
    assert "Confidence: 1.00" in result


def test_format_evidence_citations_critical_module():
    """Test formatting critical module evidence citations."""
    generator = OnboardingBriefGenerator()
    
    evidence = [
        {
            'type': 'critical_module',
            'path': 'src/main.py',
            'pagerank': 0.5,
            'exports': ['main', 'run', 'init'],
            'file': 'src/main.py',
            'line_range': (1, 50)
        }
    ]
    
    result = generator.format_evidence_citations(evidence)
    
    assert "**Critical Module:** `src/main.py`" in result
    assert "PageRank Score: 0.5000" in result
    assert "Key Exports: main, run, init" in result
    assert "`src/main.py`:1-50" in result


def test_format_evidence_citations_blast_radius():
    """Test formatting blast radius evidence citations."""
    generator = OnboardingBriefGenerator()
    
    evidence = [
        {
            'type': 'lineage_blast_radius',
            'node': 'users_table',
            'affected_count': 15,
            'affected_list': ['transform_1', 'transform_2', 'report_gen'],
            'file': 'users_table'
        }
    ]
    
    result = generator.format_evidence_citations(evidence)
    
    assert "**Blast Radius:** `users_table`" in result
    assert "Affected Components: 15" in result
    assert "Examples: transform_1, transform_2, report_gen" in result


def test_format_evidence_citations_high_velocity():
    """Test formatting high velocity module evidence citations."""
    generator = OnboardingBriefGenerator()
    
    evidence = [
        {
            'type': 'high_velocity_module',
            'path': 'src/config.py',
            'change_velocity': 45,
            'purpose': 'Configuration settings',
            'file': 'src/config.py',
            'line_range': (1, 30)
        }
    ]
    
    result = generator.format_evidence_citations(evidence)
    
    assert "**High-Change File:** `src/config.py`" in result
    assert "Commit Count: 45" in result
    assert "Purpose: Configuration settings" in result
    assert "`src/config.py`:1-30" in result


def test_format_evidence_citations_empty():
    """Test formatting empty evidence list."""
    generator = OnboardingBriefGenerator()
    
    result = generator.format_evidence_citations([])
    
    assert "No evidence available" in result


def test_write_coverage_summary(sample_day_one_answers, sample_analysis_metadata):
    """Test writing coverage summary section."""
    generator = OnboardingBriefGenerator()
    
    result = generator._write_coverage_summary(
        day_one_answers=sample_day_one_answers,
        analysis_metadata=sample_analysis_metadata
    )
    
    assert "## Coverage Summary" in result
    assert "Questions Answered:** 5/5" in result
    assert "Total Evidence Citations:" in result
    assert "Average Confidence:** 0.85" in result
    assert "25 modules" in result


def test_generate_with_missing_questions(sample_analysis_metadata):
    """Test generating brief with missing questions."""
    generator = OnboardingBriefGenerator()
    
    # Only provide two questions
    partial_answers = {
        'ingestion_path': {
            'answer': 'Test answer',
            'evidence': [],
            'provenance': ProvenanceMetadata(
                evidence_type="heuristic",
                source_file="test",
                confidence=0.5,
                resolution_status="inferred"
            )
        },
        'critical_outputs': {
            'answer': 'Test answer 2',
            'evidence': [],
            'provenance': ProvenanceMetadata(
                evidence_type="heuristic",
                source_file="test",
                confidence=0.5,
                resolution_status="inferred"
            )
        }
    }
    
    result = generator.generate(
        day_one_answers=partial_answers,
        analysis_metadata=sample_analysis_metadata
    )
    
    # Should still generate valid document
    assert "# Onboarding Brief" in result
    assert "## Question 1:" in result
    assert "## Question 2:" in result
    # Questions 3-5 should not be present
    assert "## Question 3:" not in result
    
    # Coverage summary should reflect partial answers
    assert "Questions Answered:** 2/5" in result


def test_format_evidence_citations_domain_cluster():
    """Test formatting domain cluster evidence citations."""
    generator = OnboardingBriefGenerator()
    
    evidence = [
        {
            'type': 'domain_cluster',
            'domain': 'Data Processing',
            'module_count': 8,
            'representative_modules': [
                {'path': 'src/transform.py', 'purpose': 'Data transformation', 'complexity': 50},
                {'path': 'src/validate.py', 'purpose': 'Data validation', 'complexity': 30}
            ]
        }
    ]
    
    result = generator.format_evidence_citations(evidence)
    
    assert "**Domain:** Data Processing" in result
    assert "Module Count: 8" in result
    assert "Representative Modules:" in result
    assert "`src/transform.py`" in result
    assert "Data transformation" in result
